### ISSUE TITLE
8bit在线量化失败（A10环境）

### ISSUE THREAD

**Issue by sharemen** [baichuan-inc/Baichuan-13B#108]
我在A10 24G 环境上尝试在线量化8bit 模型失败，得到输出
`Loading checkpoint shards:   0%|                                                                                                                  | 0/3 [00:00<?, ?it/s]`
`Killed`
使用原始16位精度可以启动成功，但是无法执行问答（因为显存不足）
想使用8bit量化模型跑，按照说明修改初始化代码
`model = AutoModelForCausalLM.from_pretrained(
        "baichuan-inc/Baichuan-13B-Chat",
        torch_dtype=torch.float16,
        trust_remote_code=True
    )
`
`model = model.quantize(8).cuda()`
就得到上面的结果

**Comment by sharemen** [comment]
目前推测应该是在线量化占用内存过大，导致进程被杀，这里应该说明一下执行在线量化的内存需求
同时想要下载已经量化好的版本，链接是个404

**Comment by iaston** [comment]
你的内存是多少，应该内存超出被kill了

**Comment by sharemen** [comment]
32G

**Comment by red4army** [comment]
用HuggingFace这个配置是可以正常跑的，供参考

<img width="289" alt="image" src="https://github.com/baichuan-inc/Baichuan-13B/assets/139942740/23923418-0ef4-4b07-9ebc-574505feb11c">

**Comment by sharemen** [comment]
好的
