### ISSUE TITLE
怎么切换成int4之后，推理速度变慢了

### ISSUE THREAD

**Issue by ZJ-CAI** [baichuan-inc/Baichuan-13B#119]
显存占用倒是从25G降低到了12G

**Comment by nankelli** [comment]
+1，大概降低了50%

**Comment by shesung** [comment]
只是压缩参数，计算时需要先把参数解压回fp16，当然慢啦。

**Comment by tommyjex** [comment]
> 只是压缩参数，计算时需要先把参数解压回fp16，当然慢啦。

我也很疑惑。
解压回fp16 的意义是什么呢，感觉量化使推理速度变慢，失去了量化的意义。

量化是为了能够在更多的场景中低成本用上LLM，即使量化到小显存能加载，速度变慢同样无法在真实业务里应用。

**Comment by Qbuer** [comment]
量化推理优化，优化的是显存占用需求，不是量化推理加速哈 /捂脸哭

**Comment by terrifyzhao** [comment]
> > 只是压缩参数，计算时需要先把参数解压回fp16，当然慢啦。
> 
> 我也很疑惑。 解压回fp16 的意义是什么呢，感觉量化使推理速度变慢，失去了量化的意义。
> 
> 量化是为了能够在更多的场景中低成本用上LLM，即使量化到小显存能加载，速度变慢同样无法在真实业务里应用。

量化的目的是让你在显存小的机器上能跑起来，并不代表就会快
