### ISSUE TITLE
load in 4bit和在线量化的区别？

### ISSUE THREAD

**Issue by NaCloudAI** [baichuan-inc/Baichuan-13B#121]
| Python process error: /opt/conda/lib/python3.10/site-packages/bitsandbytes/nn/modules.py:224: UserWarning: Input type into Linear4bit is torch.float16, but bnb_4bit_compute_type=torch.float32 (default). This will lead to slow inference or training speed.
0|app    |   warnings.warn(f'Input type into Linear4bit is torch.float16, but bnb_4bit_compute_type=torch.float32 (default). This will lead to slow inference or training speed.')

我发现可以直接用load_in_4_bit = True就可以加载模型不爆显存了，但是有一个推理速度的警告，请问这种方法和官方文档的在线量化区别是什么？（在线量化内存不够）

**Comment by jameswu2014** [comment]
> 

在线量化内存应该也是够的，可能没把device_map='auto'去掉。两者的区别是量化方法不一样

**Comment by Gzj369** [comment]
去掉device_map='auto'后，采用在线8bit量化Baichuan-13B，20GB的显存推理够用了
![image](https://github.com/baichuan-inc/Baichuan-13B/assets/13391430/400ba8bb-c7af-4e20-8351-c81305cfc941)
