### ISSUE TITLE
stream = True 后为什么没有随机性了。

### ISSUE THREAD

**Issue by IssacLin** [baichuan-inc/Baichuan-13B#125]
从huggingface上下载的最新的权重。路径在 /baichuan-chat-13b

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation.utils import GenerationConfig

tokenizer = AutoTokenizer.from_pretrained("/baichuan-chat-13b", use_fast=False, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("/baichuan-chat-13b", device_map="auto", torch_dtype=torch.float16, trust_remote_code=True)
model.generation_config = GenerationConfig.from_pretrained("/baichuan-chat-13b")
messages = []
messages.append({"role": "user", "content": "Which moutain is the second highest one in the world?"})
print("=== first ===")
response = model.chat(tokenizer, messages)
print(response)
print("=== second ===")
for response in model.chat(tokenizer, messages, stream = True):
    print(response)
print("=== third ===")
for response in model.chat(tokenizer, messages, stream = True):
    print(response)
```
不加 stream = True  之前是有随机性的，加了 stream = True 之后无论跑多少次结果都一样。包括 cli_demo.py 也试过了也是类似的情况。

**Comment by IssacLin** [comment]
下面是跑出来的结果

> === first ===
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which stands as the overall height leader.The next-highest mountain on Earth after Mt.Everest and part of the same range is K2 at a lofty peak of just over two miles high!
> === second ===
> The
> The H
> The Himal
> The Himalay
> The Himalayas
> The Himalayas are
> The Himalayas are home
> The Himalayas are home to
> The Himalayas are home to several
> The Himalayas are home to several of
> The Himalayas are home to several of the
> The Himalayas are home to several of the worlds
> The Himalayas are home to several of the worlds tall
> The Himalayas are home to several of the worlds tallest
> The Himalayas are home to several of the worlds tallest mountains
> The Himalayas are home to several of the worlds tallest mountains,
> The Himalayas are home to several of the worlds tallest mountains, including
> The Himalayas are home to several of the worlds tallest mountains, including Mount
> The Himalayas are home to several of the worlds tallest mountains, including Mount Ever
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,8
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,84
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 2
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,0
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,02
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet),
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earth
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Hig
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-h
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-hig
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Ever
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approx
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,6
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,61
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China
> === third ===
> The
> The H
> The Himal
> The Himalay
> The Himalayas
> The Himalayas are
> The Himalayas are home
> The Himalayas are home to
> The Himalayas are home to several
> The Himalayas are home to several of
> The Himalayas are home to several of the
> The Himalayas are home to several of the worlds
> The Himalayas are home to several of the worlds tall
> The Himalayas are home to several of the worlds tallest
> The Himalayas are home to several of the worlds tallest mountains
> The Himalayas are home to several of the worlds tallest mountains,
> The Himalayas are home to several of the worlds tallest mountains, including
> The Himalayas are home to several of the worlds tallest mountains, including Mount
> The Himalayas are home to several of the worlds tallest mountains, including Mount Ever
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,8
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,84
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 2
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,0
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,02
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet),
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earth
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Hig
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-h
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-hig
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Ever
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approx
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,6
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,61
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China
> The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China

**Comment by IssacLin** [comment]
有没有人遇到类似的问题？怎么解决，在 model.chat(tokenizer, messages, stream = True) 的模式下无论改什么配置都没有用，但是 model.chat(tokenizer, messages) 似乎不用改配置也是随机的。

**Comment by IssacLin** [comment]
generation_config.json
```
{
  "pad_token_id": 0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "user_token_id": 195,
  "assistant_token_id": 196,
  "max_new_tokens": 2048,
  "temperature": 0.3,
  "top_k": 5,
  "top_p": 0.85,
  "repetition_penalty": 1.1,
  "do_sample": true,
  "transformers_version": "4.29.2"
}
```

**Comment by MarvinLong** [comment]
同样的问题，感觉得去看下 NewGenerationMixin.generate 的实现。目前我的库是 4.31.0, 我看官方的gen config是 4.29.2
`    @torch.no_grad()
    def chat(self, tokenizer, messages: List[dict], stream=False,
             generation_config: Optional[GenerationConfig]=None):
        generation_config = generation_config or self.generation_config
        input_ids = self._build_chat_input(tokenizer, messages, generation_config.max_new_tokens)
        if stream:
            from transformers_stream_generator.main import NewGenerationMixin, StreamGenerationConfig
            self.__class__.generate = NewGenerationMixin.generate
            self.__class__.sample_stream = NewGenerationMixin.sample_stream
            stream_config = StreamGenerationConfig(**generation_config.to_dict(), do_stream=True)

            def stream_generator():
                outputs = []
                for token in self.generate(input_ids, generation_config=stream_config):
                    outputs.append(token.item())
                    yield tokenizer.decode(outputs, skip_special_tokens=True)

            return stream_generator()
        else:
            self.__class__.generate = PreTrainedModel.generate  # disable stream
            outputs = self.generate(input_ids, generation_config=generation_config)
            response = tokenizer.decode(outputs[0][len(input_ids[0]):], skip_special_tokens=True)
            return response`

**Comment by IssacLin** [comment]
但是有一个新的问题。
当配置文件里面 `"do_sample": false`的时候，会报错。
`RuntimeError: a Tensor with 120 elements cannot be converted to Scalar`
不知道走到哪一步出现的报错，所以暂时就先让他一定会随机。
