### ISSUE TITLE
Baichuan tokenizer对诗词分词不准确

### ISSUE THREAD

**Issue by CanvaChen** [baichuan-inc/Baichuan-13B#161]
“白日依山尽，黄河入海流。欲穷千里目，更上一层楼。” 
分词结果如下：
['白', '日', '依', '山', '尽', '，', '黄河', '入', '海', '流', '。', '欲', '穷', '千里', '目', '，', '更', '上一', '层', '楼', '。']

“上一”在一块不合理。

**Comment by jcdiv47** [comment]
> 原因已知

可以分享一下原因嘛？
