### ISSUE TITLE
请提供int8的模型下载

### ISSUE THREAD

**Issue by terryops** [baichuan-inc/Baichuan-13B#17]
不然每次运行都需要很长的时间使用CPU进行量化。
请大家注意，这个模型即使用量化int8去跑，也是需要64G内存的。但是量化完之后，就只占用25G左右。
测试效果是比ChatGLM强很多，但是远远比不上GPT4，很多地方也比不上GPT3.5。
想微调的可以试试，日常使用就算了。

**Comment by Cat-L** [comment]
+1

**Comment by wzwtime** [comment]
+1

**Comment by GradientGuru** [comment]
已提供Chat版本。见更新后的README

**Comment by GuohongLi** [comment]
> 已提供Chat版本。见更新后的README

@GradientGuru https://huggingface.co/baichuan-inc/Baichuan-13B-Chat-int8 404了

**Comment by jiacheo** [comment]
[Baichuan-13B-Chat-int8](https://huggingface.co/baichuan-inc/Baichuan-13B-Chat-int8)
又删掉了？
