### ISSUE TITLE
本地部署版本问题

### ISSUE THREAD

**Issue by JasonFlyBeauty** [baichuan-inc/Baichuan-13B#196]
请问本地部署时的transformer的版本用的多少呀
我的是4.36.0.dev0，报错
    return self.sp_model.get_piece_size()
           ^^^^^^^^^^^^^
AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'

**Comment by DeoLeung** [comment]
遇到相同问题, 需要downgrade到多少?

**Comment by DeoLeung** [comment]
`4.33.3` works
