### ISSUE TITLE
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_baichuan. Run `pip install configuration_baichuan`

### ISSUE THREAD

**Issue by luohao123** [baichuan-inc/Baichuan-13B#22]
ImportError: This modeling file requires the following packages that were not found in your environment: configuration_baichuan. Run `pip install configuration_baichuan`

**Comment by xiaozhu1106** [comment]
同样问题+1

**Comment by EircYangQiXin** [comment]
大佬解决了吗

**Comment by EircYangQiXin** [comment]
> 这个文件在模型所在目录下，所以要在模型所在的目录下运行。

啥意思？在下载的模型目录下运行训练脚本？

**Comment by yhx0105** [comment]
+1,大佬有解决吗
