### ISSUE TITLE
最大长度能不能进一步增大？

### ISSUE THREAD

**Issue by runningBolin** [baichuan-inc/Baichuan-13B#24]

**Comment by runningBolin** [comment]
chatglm2-6b用FlashAttention增大了context长度，百川有没有同样的计划？

**Comment by cbqin** [comment]
> chatglm2-6b用FlashAttention增大了context长度，百川有没有同样的计划？

https://lmsys.org/blog/2023-06-29-longchat/

**Comment by GradientGuru** [comment]
感谢建议。我们会在后续迭代中关注long context问题
