### ISSUE TITLE
如果想用指令数据finetune Baichuan-13B-Chat，应该使用什么样的prompt模板？

### ISSUE THREAD

**Issue by egrcc** [baichuan-inc/Baichuan-13B#25]
看给出的示例都是直接model.chat来生成的，不知道内部使用的prompt模板是什么呢？

**Comment by xusenlinzy** [comment]
根据给出的模型代码，prompt模板应该是  **"<reserved_102>:{query}\n<reserved_103>{answer}"**

**Comment by egrcc** [comment]
> 

看代码好像没有中间那个换行符？

**Comment by egrcc** [comment]
> 根据给出的模型代码，prompt模板应该是 **"<reserved_102>:{query}\n<reserved_103>{answer}"**

@xusenlinzy 看代码好像没有中间那个换行符？

**Comment by xusenlinzy** [comment]
是的，没注意，应该 **"<reserved_102>:{query}<reserved_103>{answer}"**

**Comment by lucasjinreal** [comment]
应该是不对的，bc13b 默认是id拼接，你这个encode之后开头会有一个空格，并且每一轮对话都会有。

**Comment by MathYang** [comment]
> 根据给出的模型代码，prompt模板应该是 **"<reserved_102>:{query}\n<reserved_103>{answer}"**

请问这个是从哪里看出来的？

**Comment by lucasjinreal** [comment]
另外根本没有`:`

**Comment by xusenlinzy** [comment]
> > 根据给出的模型代码，prompt模板应该是 **"<reserved_102>:{query}\n<reserved_103>{answer}"**
> 
> 请问这个是从哪里看出来的？

正确的是这个，上面已经修正了，**"<reserved_102>{query}<reserved_103>{answer}"**

从huggingface上的代码可以看出来：https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/blob/f5f47be2adbbdceb784f334d6fa1ca2c73e65097/modeling_baichuan.py#L502

**user_token_id：195 -> <reserved_102>**
**assistant_token_id: 196 -> <reserved_103>**

**Comment by lucasjinreal** [comment]
这个也是错误的，这个字符串encode出来的id跟baichuan拼接的id是不同的

**Comment by xusenlinzy** [comment]
测试了一下，字符串encode出来的结果确实和代码中id拼接的结果不一样

**Comment by egrcc** [comment]
> 测试了一下，字符串encode出来的结果确实和代码中id拼接的结果不一样

@xusenlinzy 不一样吗？我测试是一样的，除了开头会多一个空格的id。感觉这个应该影响不大，或者直接去掉第一个id就行了。

**Comment by xusenlinzy** [comment]
```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("/data/checkpoints/baichuan-13b-chat/", trust_remote_code=True)

# 1. 字符串拼接方式
tokenizer.encode("<reserved_102>你好<reserved_103>我是人工智能助理")
# [31106, 195, 25211, 196, 8529, 22073, 19745]

# 2. id拼接方式
[195] + tokenizer.encode("你好") + [196] + tokenizer.encode("我是人工智能助理")
# [195, 9875, 31213, 196, 6323, 31161, 22073, 19745]
```

**Comment by egrcc** [comment]
@GradientGuru 百川的同学能回复一下吗？你们训练chat模型的时候是采用哪一种方式来拼接的？

**Comment by lucasjinreal** [comment]
你自己拿带有空格的丢进去推理一下就就知道了，结果是完全错乱的。。。不要人云亦云

**Comment by egrcc** [comment]
> 
<img width="1295" alt="截屏2023-07-14 16 38 02" src="https://github.com/baichuan-inc/Baichuan-13B/assets/6469953/832bfaf7-cccb-40ed-9c84-178afee021ac">

@lucasjinreal 我测试过，并没有完全错乱吧？你的测试case是什么？

**Comment by egrcc** [comment]
<img width="1325" alt="截屏2023-07-14 16 50 08" src="https://github.com/baichuan-inc/Baichuan-13B/assets/6469953/9b931cba-6d0a-40dd-a669-f398a3b0243a">
多轮的好像也是正常的

**Comment by jiacheo** [comment]
每一轮后面要加个 eos token （</s>）吧？

参考：https://colab.research.google.com/drive/1V4Kk6sT6LCqJ6paEXTM7Cxf6c15kbmeG#scrollTo=wCkBtPiZdeRs

```
messages = [{"role":"user", "content":"你好"},{"role":"assistant", "content":"请问有什么可以帮你？"},{"role":"user", "content":"没事，退下吧"}]
```

组装后，变成  
```
 <reserved_102> 你好<reserved_103> 请问有什么可以帮你？</s><reserved_102> 没事，退下吧<reserved_103>
```

**Comment by xusenlinzy** [comment]
> 每一轮后面要加个 eos token （</s>）吧？
> 
> 参考：https://colab.research.google.com/drive/1V4Kk6sT6LCqJ6paEXTM7Cxf6c15kbmeG#scrollTo=wCkBtPiZdeRs
> 
> ```
> messages = [{"role":"user", "content":"你好"},{"role":"assistant", "content":"请问有什么可以帮你？"},{"role":"user", "content":"没事，退下吧"}]
> ```
> 
> 组装后，变成
> 
> ```
>  <reserved_102> 你好<reserved_103> 请问有什么可以帮你？</s><reserved_102> 没事，退下吧<reserved_103>
> ```

我测试了一下，如果使用模板：**"<reserved_102> {}<reserved_103> "**，结果如下：

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("/data/checkpoints/baichuan-13b-chat/", trust_remote_code=True)

# 1. 字符串拼接方式
tokenizer.encode("<reserved_102> 你好<reserved_103> 我是人工智能助理</s>")
# [31106, 195, 9875, 31213, 196, 6323, 31161, 22073, 19745, 2]

tokenizer.encode("<reserved_102> 你好<reserved_103> 请问有什么可以帮你？</s><reserved_102> 没事，退下吧<reserved_103>")
# [31106, 195, 9875, 31213, 196, 31106, 20389, 7713, 1231, 17346, 75, 2, 31106, 195, 31106, 25639, 72, 31991, 31214, 31793, 196]

# 2. id拼接方式
[195] + tokenizer.encode("你好") + [196] + tokenizer.encode("我是人工智能助理") + [2]
# [195, 9875, 31213, 196, 6323, 31161, 22073, 19745, 2]

[195] + tokenizer.encode("你好") + [196] + tokenizer.encode("请问有什么可以帮你？") + [2, 195] + tokenizer.encode("没事，退下吧") + [196]
# [195, 9875, 31213, 196, 31106, 20389, 7713, 1231, 17346, 75, 2, 195, 31106, 25639, 72, 31991, 31214, 31793, 196]
```

这样两种方式的唯一区别就在于每轮对话多了一个31106（空格）

**Comment by lucasjinreal** [comment]
[31106, 195, 9875, 31213, 196] 和
[195, 9875, 31213, 196] 推理的结果显然是不一样的，多测试几个样本以免误导他人

**Comment by Jeffwan** [comment]
https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/commit/dcbaaf5d7238da3161c086fc8308bcee3553c05e 4天前模型进行了修改, 已经不用 </s> 了. 目前唯一差异就是31106, 没有做过大量测试确实不知道区别

**Comment by wac81** [comment]
这个问题其实是baichuan1 tokenizer问题，比如同样token  "北京" 会有两个token_id, 这导致encode时候错误，baichuan2和chatglm3都没有问题，无论用哪种方式。
