### ISSUE TITLE
商用咨询

### ISSUE THREAD

**Issue by Louis-y-nlp** [baichuan-inc/Baichuan-13B#3]
看介绍中提到，base 模型申请后可以商用，chat模型没有明确说明，可以商用吗？

**Comment by GradientGuru** [comment]
Baichuan-13B 可以申请商用。它包含 Base 和 Chat 两个版本。

**Comment by Louis-y-nlp** [comment]
感谢回复。

**Comment by lj163ucas** [comment]
> Baichuan-13B 可以申请商用。它包含 Base 和 Chat 两个版本。

商用需要授权费吗？

**Comment by Louis-y-nlp** [comment]
@GradientGuru 你好，看到hf上删除了商用许可协议，是不让商用了吗？还是放弃商用许可协议了。

**Comment by wangzuohao** [comment]
可以商用，估计也要授权费
