### ISSUE TITLE
重大问题：  model.get_input_embeddings() 报错 ---->  raise NotImplementedError

### ISSUE THREAD

**Issue by 506610466** [baichuan-inc/Baichuan-13B#30]
```
model = AutoModelForCausalLM.from_pretrained(
            'baichuan-inc/Baichuan-13B-Chat',
            device_map='auto,
            trust_remote_code=True,
        )
model.get_input_embeddings()
```
model.get_input_embeddings()   会报错
提示：raise NotImplementedError
![9a7b3ddc307811439b33e85edec5895](https://github.com/baichuan-inc/Baichuan-13B/assets/39985245/3c42a0ea-136f-48f0-882e-1320eaa46315)

**Comment by 506610466** [comment]
我让其他人尝试，也是报同样的错误。

**Comment by GradientGuru** [comment]
已更新HF。pull 最新代码测一下

**Comment by qiyuan-chen** [comment]
更新到transformers 4.31.0.dev0后还是不行

**Comment by qiyuan-chen** [comment]
> ```
> model = AutoModelForCausalLM.from_pretrained(
>             'baichuan-inc/Baichuan-13B-Chat',
>             device_map='auto,
>             trust_remote_code=True,
>         )
> model.get_input_embeddings()
> ```
> 
> model.get_input_embeddings() 会报错 提示：raise NotImplementedError ![9a7b3ddc307811439b33e85edec5895](https://user-images.githubusercontent.com/39985245/252881937-3c42a0ea-136f-48f0-882e-1320eaa46315.png)

请问你解决了吗？

**Comment by 506610466** [comment]
> > ```
> > model = AutoModelForCausalLM.from_pretrained(
> >             'baichuan-inc/Baichuan-13B-Chat',
> >             device_map='auto,
> >             trust_remote_code=True,
> >         )
> > model.get_input_embeddings()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > model.get_input_embeddings() 会报错 提示：raise NotImplementedError ![9a7b3ddc307811439b33e85edec5895](https://user-images.githubusercontent.com/39985245/252881937-3c42a0ea-136f-48f0-882e-1320eaa46315.png)
> 
> 请问你解决了吗？
问题已解决 需要重新下载这个文件
<img width="1156" alt="76e615cd6ea58fddea4f599afdfd161" src="https://github.com/baichuan-inc/Baichuan-13B/assets/39985245/bd5a9b46-52b5-4c98-bb9a-59811f34773d">
