### ISSUE TITLE
为什么没有和chatglm的数据对比？

### ISSUE THREAD

**Issue by yangbisheng2009** [baichuan-inc/Baichuan-13B#33]

**Comment by thomas-young-2013** [comment]
通问Baichuan-13B-chat vs. ChatGLM2

**Comment by liaoweiguo** [comment]
参数量决定了逻辑性。6B几乎没有逻辑，13好一丢丢吧。

**Comment by liaoweiguo** [comment]
c-eval chatglm2大幅领先，不科学啊

**Comment by CRGBS** [comment]
![圖片](https://github.com/baichuan-inc/Baichuan-13B/assets/32331418/93c5f82c-db78-46af-a0c4-1feefacf4a9f)
@liaoweiguo 參數量不同
chatglm2 一種是6b一種是130b的
看起來baichuan是優於glm的

**Comment by WingsLong** [comment]
> 



> ![圖片](https://user-images.githubusercontent.com/32331418/252984424-93c5f82c-db78-46af-a0c4-1feefacf4a9f.png) @liaoweiguo 參數量不同 chatglm2 一種是6b一種是130b的 看起來baichuan是優於glm的

这个图片是哪里来的，能否给个链接

**Comment by CRGBS** [comment]
@WingsLong 
https://cevalbenchmark.com/static/leaderboard.html

**Comment by WingsLong** [comment]
> @WingsLong https://cevalbenchmark.com/static/leaderboard.html

谢谢

**Comment by iluhcm** [comment]
> c-eval chatglm2大幅领先，不科学啊

第一个ChatGLM2的模型是不是130B的模型，还没有开源吧，参数量不在一个层级

**Comment by tanguofu** [comment]
> 

请问这个数据的来源是在哪里？
