### ISSUE TITLE
配置文件里面是do_sample是true，但是为什么没有随机性

### ISSUE THREAD

**Issue by IssacLin** [baichuan-inc/Baichuan-13B#36]
配置文件里面是do_sample是true，但是为什么没有随机性

**Comment by IssacLin** [comment]
{
  "pad_token_id": 0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "user_token_id": 195,
  "assistant_token_id": 196,
  "max_new_tokens": 2048,
  "temperature": 0.3,
  "top_k": 5,
  "top_p": 0.85,
  "repetition_penalty": 1.1,
  "do_sample": true,
  "transformers_version": "4.29.2"
}

**Comment by GradientGuru** [comment]
给一下推理代码看看

**Comment by IssacLin** [comment]
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation.utils import GenerationConfig

tokenizer = AutoTokenizer.from_pretrained("/baichuan-chat-13b", use_fast=False, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained("/baichuan-chat-13b", device_map="auto", torch_dtype=torch.float16, trust_remote_code=True)
model.generation_config = GenerationConfig.from_pretrained("/baichuan-chat-13b")
messages = []
messages.append({"role": "user", "content": "Which moutain is the second highest one in the world?"})
print("=== first ===")
response = model.chat(tokenizer, messages)
print(response)
print("=== second ===")
for response in model.chat(tokenizer, messages, stream = True):
    print(response)
print("=== third ===")
for response in model.chat(tokenizer, messages, stream = True):
    print(response)

**Comment by IssacLin** [comment]
=== first ===
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which stands as the overall height leader.The next-highest mountain on Earth after Mt.Everest and part of the same range  is K2 at a lofty peak of just over two miles high!
=== second ===
The
The H
The Himal
The Himalay
The Himalayas
The Himalayas are
The Himalayas are home
The Himalayas are home to
The Himalayas are home to several
The Himalayas are home to several of
The Himalayas are home to several of the
The Himalayas are home to several of the worlds
The Himalayas are home to several of the worlds tall
The Himalayas are home to several of the worlds tallest
The Himalayas are home to several of the worlds tallest mountains
The Himalayas are home to several of the worlds tallest mountains,
The Himalayas are home to several of the worlds tallest mountains, including
The Himalayas are home to several of the worlds tallest mountains, including Mount
The Himalayas are home to several of the worlds tallest mountains, including Mount Ever
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,8
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,84
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 2
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,0
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,02
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet),
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earth
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Hig
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-h
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-hig
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Ever
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approx
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,6
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,61
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China
=== third ===
The
The H
The Himal
The Himalay
The Himalayas
The Himalayas are
The Himalayas are home
The Himalayas are home to
The Himalayas are home to several
The Himalayas are home to several of
The Himalayas are home to several of the
The Himalayas are home to several of the worlds
The Himalayas are home to several of the worlds tall
The Himalayas are home to several of the worlds tallest
The Himalayas are home to several of the worlds tallest mountains
The Himalayas are home to several of the worlds tallest mountains,
The Himalayas are home to several of the worlds tallest mountains, including
The Himalayas are home to several of the worlds tallest mountains, including Mount
The Himalayas are home to several of the worlds tallest mountains, including Mount Ever
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,8
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,84
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 2
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,0
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,02
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet),
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earth
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Hig
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-h
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-hig
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Ever
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approx
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,6
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,61
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China
The Himalayas are home to several of the worlds tallest mountains, including Mount Everest (8,848 meters or 29,029 feet), which holds the title of being the Earths Highest Peak.The next-highest mountain on this list after Mt.Everest would be K2 at a height of approximately 8,611 metres high and located within Pakistan near its border with China

**Comment by IssacLin** [comment]
不加 stream = True 的时候是有随机性的，加了 stream = True 后跑多次都没有随机性。

**Comment by bc-gpd** [comment]
已更新生成代码，可以重新拉取一下huggingface的最新代码尝试一下
