### ISSUE TITLE
AttributeError: 'BaiChuanForCausalLM' object has no attribute 'chat'

### ISSUE THREAD

**Issue by wanglaiqi** [baichuan-inc/Baichuan-13B#42]

**Comment by GradientGuru** [comment]
本来就没有chat()

**Comment by wanglaiqi** [comment]
[]([]([]([]([](![4671a2df54815eeff4efb2b5732eaa0](https://github.com/baichuan-inc/Baichuan-13B/assets/9366714/6fd21eb6-996c-44b3-b42b-8310fc54285b))))))
没有chat ,所以这个地方掉不通

**Comment by zoeChen119** [comment]
那这个地方应该用什么？为什么issue中的微调方案都是chat

**Comment by wanglaiqi** [comment]
> 那这个地方应该用什么？为什么issue中的微调方案都是chat

7B模型没有chat函数，， 13B模型可以用 model.chat进行生成结果。

用自己的数据微调可以用13b-base也可以用13b-chat模型

**Comment by wertyhb-sns** [comment]
你好 那怎么用7B运行呀？删掉chat调用嘛？

**Comment by wertyhb-sns** [comment]
> for response in model.chat(tokenizer, messages, stream=True): placeholder.markdown(response) if torch.backends.mps.is_available(): torch.mps.empty_cache() 没有chat ,所以这个地方掉不通

你好 你怎么解决的呀？
