### ISSUE TITLE
什么时候有量化后的模型

### ISSUE THREAD

**Issue by 15899885850** [baichuan-inc/Baichuan-13B#48]
RT
现在每次启动都需要使用CPU量化，速度太慢了

**Comment by jameswu2014** [comment]
这两天会发布

**Comment by ShadowPower** [comment]
可以试试 bitsandbytes 量化，我写了一篇教程：
https://zhuanlan.zhihu.com/p/643307410

**Comment by GradientGuru** [comment]
已经有Chat的量化版本。见更新后的README

**Comment by Gzj369** [comment]
@GradientGuru 大佬，Chat的量化版本链接好像失效了，无法下载，麻烦帮忙看看

**Comment by Gzj369** [comment]
找到了，可以用这个链接访问下载 8bit量化后的模型，https://huggingface.co/trillionmonster/Baichuan-13B-Chat-8bit/tree/main
