### ISSUE TITLE
lora训练报错 ValueError: Please specify `target_modules` in `peft_config`

### ISSUE THREAD

**Issue by delltower** [baichuan-inc/Baichuan-13B#52]
/root/anaconda3/envs/lmflow_v3/lib/python3.9/site-packages/lmflow-0.0.1-py3.9.egg/lmflow/models/ │
│ auto_model.py:16 in get_model                                                                    │
│                                                                                                  │
│   13 │   def get_model(self, model_args, *args, **kwargs):                                       │
│   14 │   │   arch_type = model_args.arch_type                                                    │
│   15 │   │   if arch_type == "decoder_only":                                                     │
│ ❱ 16 │   │   │   return HFDecoderModel(model_args, *args, **kwargs)                              │
│   17 │   │   elif arch_type == "text_regression":                                                │
│   18 │   │   │   return TextRegressionModel(model_args, *args, **kwargs)                         │
│   19 │   │   elif arch_type == "encoder_decoder":                                                │
│                                                                                                  │
│ /root/anaconda3/envs/lmflow_v3/lib/python3.9/site-packages/lmflow-0.0.1-py3.9.egg/lmflow/models/ │
│ hf_decoder_model.py:222 in __init__                                                              │
│                                                                                                  │
│   219 │   │   │   │   │   lora_dropout=model_args.lora_dropout,                                  │
│   220 │   │   │   │   │   target_modules=lora_target_modules,                                    │
│   221 │   │   │   │   )                                                                          │
│ ❱ 222 │   │   │   │   model = get_peft_model(model, peft_config)                                 │
│   223 │   │   │   │   model.print_trainable_parameters()                                         │
│   224 │   │   │                                                                                  │
│   225 │   │   │   # We resize the embeddings only when necessary to avoid index errors.          │
│                                                                                                  │
│ /root/anaconda3/envs/lmflow_v3/lib/python3.9/site-packages/peft/mapping.py:145 in get_peft_model │
│                                                                                                  │
│   142 │   │   peft_config = _prepare_lora_config(peft_config, model_config)                      │
│   143 │   │   return PeftModel(model, peft_config)                                               │
│   144 │   if not isinstance(peft_config, PromptLearningConfig):                                  │
│ ❱ 145 │   │   peft_config = _prepare_lora_config(peft_config, model_config)                      │
│   146 │   else:                                                                                  │
│   147 │   │   peft_config = _prepare_prompt_learning_config(peft_config, model_config)           │
│   148 │   return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](model, peft_config)     │
│                                                                                                  │
│ /root/anaconda3/envs/lmflow_v3/lib/python3.9/site-packages/peft/mapping.py:120 in                │
│ _prepare_lora_config                                                                             │
│                                                                                                  │
│   117 │   if peft_config.target_modules is None:                                                 │
│   118 │   │   print(TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING)                          │
│   119 │   │   if model_config["model_type"] not in TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_   │
│ ❱ 120 │   │   │   raise ValueError("Please specify `target_modules` in `peft_config`")           │
│   121 │   │   peft_config.target_modules = TRANSFORMERS_MODELS_TO_LORA_TARGET_MODULES_MAPPING[   │
│   122 │   if len(peft_config.target_modules) == 1:                                               │
│   123 │   │   peft_config.fan_in_fan_out = True                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Please specify `target_modules` in `peft_config`

**Comment by supinyu** [comment]
@delltower  你需要在peft_config里面设置target_modules，

https://github.com/supinyu/Goat-Math-Chinese/blob/main/train_lora.py

你可以参考这个代码，设置target_modules为["W_pack", "o_proj"]
