### ISSUE TITLE
如何不自动更新？

### ISSUE THREAD

**Issue by huanyeruqiu** [baichuan-inc/Baichuan-13B#57]
这个项目模型下了好几遍，本身huggingface的网络就不是很稳定，这几天光不停下模型了。好不容易下载好了，第二天运行一下，又重新开始下载几十G的文件了。怎么样才能禁止更新，我不想要联网使用也不想要更新，谢谢各位大佬

**Comment by fenglinbei** [comment]
把模型原始文件copy一份出来，后面读取模型直接从路径读取

**Comment by huanyeruqiu** [comment]
> 把模型原始文件copy一份出来，后面读取模型直接从路径读取

好的谢谢，不过我不懂AI的专业知识，不了解如何直接路径读取，官方不给方案，只能自己再查查资料了
