### ISSUE TITLE
请问baichuan-13b如何训练/微调喂自己的数据？

### ISSUE THREAD

**Issue by bxjxxyy** [baichuan-inc/Baichuan-13B#58]
请问baichuan-13b如何训练/微调喂自己的数据？
看到有一些框架说是支持baichuan-13b的训练。还是希望官方能有一个官方的训练方式

**Comment by GradientGuru** [comment]
https://github.com/hiyouga/LLaMA-Efficient-Tuning
可以参考这个项目
