### ISSUE TITLE
为何24g做int8推理，也out of memory

### ISSUE THREAD

**Issue by zhangyunming** [baichuan-inc/Baichuan-13B#6]
![image](https://github.com/baichuan-inc/Baichuan-13B/assets/12590457/2e0db4a0-5659-4cc7-851d-e8125d5b97b9)
您好，我按照您写的，在cli_demo.py中加了一行代码，但是在3090显卡上还是显示显存不足，是下载的模型本身就是F16的吗

**Comment by jameswu2014** [comment]
你需要去掉device_map=‘auto',那行会自动把你的fp16模型放到gpu上的，导致显存不足

**Comment by zhangyunming** [comment]
![image](https://github.com/baichuan-inc/Baichuan-13B/assets/12590457/b2bae9e1-1a8b-4534-b418-0674928378c2)
@jameswu2014 您好  我已经去掉这一行，但是运行python cli_demo.py的时候就一直停留在如上图那样，没有加载模型并继续

**Comment by stuarthe** [comment]
> 你需要去掉device_map=‘auto',那行会自动把你的fp16模型放到gpu上的，导致显存不足

是的。官方有说明。这里的量化，是在线量化，需要把模型加载到内存，量化后再放到显存。所以需要去掉 device_map=‘auto'
