### ISSUE TITLE
HuggingFace上int8量化版本链接失效

### ISSUE THREAD

**Issue by 15899885850** [baichuan-inc/Baichuan-13B#61]
RT 显示404 https://huggingface.co/baichuan-inc/Baichuan-13B-Chat-int8

**Comment by jameswu2014** [comment]
还没有开放出来，目前仓库还是private，得等等。

**Comment by GradientGuru** [comment]
现在好了

**Comment by z2n** [comment]
> 现在好了

int8 版链接仍然 404，是不是还是 private.
