### ISSUE TITLE
通过api接口调用，每个问题单独的，连续问，为什么前10个问题回答还挺准确，但超过10个后回答就错乱了

### ISSUE THREAD

**Issue by chelovek21** [baichuan-inc/Baichuan-13B#63]
通过api接口调用，每个问题单独的，连续问，为什么前10个问题回答还挺准确，但超过10个后回答就错乱了。将use_cache置为False也没用，是model.chat内置会记录历史问答信息吗？

**Comment by fenglinbei** [comment]
模型上下文窗口大小有限，对话多了上下文太大了回答就乱了

**Comment by chelovek21** [comment]
谢谢，但是还是有疑问。我每个问题是单独的，通过api调用模型，不是一个连续会话形式，他为什么会记录上一次的会话，或者说，现在我有个私有数据集，我想测试他在私有数据集下的表现，应该如何调用？不应该就是单独cli_api部署，然后通过api去调用吗？

**Comment by fenglinbei** [comment]
我目前使用没出现过这个问题
你检查一下cli_api里面收到的history里面有没有别的数据，不行的话在每次api调用的时候加个
`torch.cuda.empty_cache()`
试试
