### ISSUE TITLE
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'，加入int8量化能推理，去掉之后就报这个错

### ISSUE THREAD

**Issue by YinSonglin1997** [baichuan-inc/Baichuan-13B#65]
![1689343622561](https://github.com/baichuan-inc/Baichuan-13B/assets/90330685/5c8f208d-efa7-45ef-bea7-7395f7ae116d)

**Comment by YinSonglin1997** [comment]
解决了，多GPU要把device_map="auto"取消注释

**Comment by wccccp** [comment]
> 解决了，多GPU要把device_map="auto"取消注释

我取消了注释，但是还是在报错。。
