### ISSUE TITLE
cli_demo.py 切换Baichuan-13B-Chat 问答异常

### ISSUE THREAD

**Issue by xuxiaosheng0606** [baichuan-inc/Baichuan-13B#67]
切换模型代码：
def init_model():
    print("init model ...")
    model = AutoModelForCausalLM.from_pretrained(
        "baichuan-inc/Baichuan-13B-Base",
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
    model.generation_config = GenerationConfig.from_pretrained(
        "baichuan-inc/Baichuan-13B-Base"
    )
    tokenizer = AutoTokenizer.from_pretrained(
        "baichuan-inc/Baichuan-13B-Base",
        use_fast=False,
        trust_remote_code=True
    )
    return model, tokenizer

异常信息：
欢迎使用百川大模型，输入进行对话，clear 清空历史，CTRL+C 中断生成，steam 开关流式生成，exit 结束。

用户：你好

Baichuan：Traceback (most recent call last):
File "/root/Baichuan-13B/cli_demo_base.py", line 72, in
main()
File "/root/Baichuan-13B/cli_demo_base.py", line 57, in main
for response in model.chat(tokenizer, messages, stream=True):
File "/root/envs/baichuan13b/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Base/modeling_baichuan.py", line 536, in chat
input_ids = self._build_chat_input(tokenizer, messages, generation_config.max_new_tokens)
File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Base/modeling_baichuan.py", line 504, in _build_chat_input
max_input_tokens = self.config.model_max_length - max_new_tokens
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

请帮忙看下是什么原因

**Comment by fenglinbei** [comment]
> model.generation_config = GenerationConfig.from_pretrained( "baichuan-inc/Baichuan-13B-Base" ) 
参数没设置对

**Comment by xuxiaosheng0606** [comment]
抱歉标题写错了， 我是使用cli_demo.py 从Baichuan-13B-Chat切换为Baichuan-13B-Base，Baichuan-13B-Chat可以正常使用，切换为Baichuan-13B-Base时，启动成功，问答时报错：
如下：

用户：你好

Baichuan：Traceback (most recent call last):
File "/root/Baichuan-13B/cli_demo_base.py", line 72, in
main()
File "/root/Baichuan-13B/cli_demo_base.py", line 57, in main
for response in model.chat(tokenizer, messages, stream=True):
File "/root/envs/baichuan13b/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Base/modeling_baichuan.py", line 536, in chat
input_ids = self._build_chat_input(tokenizer, messages, generation_config.max_new_tokens)
File "/root/.cache/huggingface/modules/transformers_modules/Baichuan-13B-Base/modeling_baichuan.py", line 504, in _build_chat_input
max_input_tokens = self.config.model_max_length - max_new_tokens
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**Comment by fenglinbei** [comment]
模型初始化的时候试一下这段代码
            ```
config = GenerationConfig(**{
                "assistant_token_id": 196,
                "bos_token_id": 1,
                "do_sample": False,
                "eos_token_id": 2,
                "max_new_tokens": 500,
                "pad_token_id": 0,
                "repetition_penalty": 1.1,
                "temperature": 0.3,
                "top_k": 5,
                "top_p": 0.85,
                "transformers_version": "4.30.2",
                "user_token_id": 195
                })
            model.generation_config = config
```

**Comment by heber** [comment]
初始化用上面那段代码，还是报如下错误：
Baichuan: Traceback (most recent call last):File "/home/xxx/Workspace/bigmodels/Baichuan-13B/cli_demo.py", line 92， in <module>
main(File "/home/xxx/Workspace/bigmodels /Baichuan-13B/cli demo.py", line 73， in mainfor response in model.chat(tokenizer, messages, stream=True ):File "/home/xxx/.cache/huggingface/modules/transformersmodules/Baichuan-13B-Base/modeling baichuan.py"line 599,in stream generator
outputs .append( token .item( ))
RuntimeError:a lensor with 84 ements cannot be converted to Scalar

**Comment by kg-nlp** [comment]
同样的错误

**Comment by peng06051126** [comment]
同样的错误

**Comment by she11s** [comment]
想问一下这个找到解决方案了吗？

**Comment by fenglinbei** [comment]
> 
```
config = GenerationConfig(**{
                "assistant_token_id": 196,
                "bos_token_id": 1,
                "do_sample": True,
                "eos_token_id": 2,
                "max_new_tokens": max_new_tokens,
                "pad_token_id": 0,
                "repetition_penalty": 1.1,
                "temperature": temperature,
                "top_k": top_k,
                "top_p": top_p,
                "transformers_version": "4.30.2",
                "user_token_id": 195
                })
            messages = []
            messages.append({"role": "user", "content": prompt})
            response = self.model.chat(self.tokenizer, messages, generation_config=config)

```
问答输入时，按如下方式设置参数

**Comment by kevinew** [comment]
然后就报这个错了 AttributeError: 'GenerationConfig' object has no attribute 'user_token_id'. Did you mean: 'bos_token_id'?

**Comment by aooxin** [comment]
> 然后就报这个错了 AttributeError: 'GenerationConfig' object has no attribute 'user_token_id'. Did you mean: 'bos_token_id'?

同问

**Comment by ckqqqq** [comment]
同问

**Comment by Dingss1** [comment]
transformers版本问题，使用4.32.0可以

**Comment by Zhengyan1224** [comment]
> transformers版本问题，使用4.32.0可以

我就是4.32.0一样有这个问题
