### ISSUE TITLE
Baichuan-13B-Chat的评估

### ISSUE THREAD

**Issue by xianghuisun** [baichuan-inc/Baichuan-13B#69]
请问能否发出 在Ceval和CMMLU上评估Baichuan-13B-Chat的评估代码呢

评估Baichuan-13B-Base的分数是可以复现的。但是对于Baichuan-13B-Chat，
我自己评测后发现Baichuan-13B-Chat在这两个数据集上的分数都很低，不知道是哪里的问题。

**Comment by chelovek21** [comment]
同问，我遇到类似问题，连续多个问题，每个问题是独立的，通过api调用访问，前面几个的问题回答挺正常，但后面回答就有点错乱了。不知道是否调用方式有区别或者那个参数需要调整，没有找到正确调用的办法。

**Comment by benywon** [comment]
可以通过我们-baichuan-7b的脚本进行评估。https://github.com/baichuan-inc/Baichuan-7B

**Comment by xianghuisun** [comment]
> 可以通过我们-baichuan-7b的脚本进行评估。https://github.com/baichuan-inc/Baichuan-7B

你好，我用的就是这个脚本。
base模型可以复现，但是chat版本的分数就很低

**Comment by sichehu** [comment]
> 请问能否发出 在Ceval和CMMLU上评估Baichuan-13B-Chat的评估代码呢
> 
> 评估Baichuan-13B-Base的分数是可以复现的。但是对于Baichuan-13B-Chat， 我自己评测后发现Baichuan-13B-Chat在这两个数据集上的分数都很低，不知道是哪里的问题。

我也是，我复现的评估结果是0.47591049990243933 很明显低于给出的结果

**Comment by EricLingRui** [comment]
Chat 的复现需要考虑是否用 user_token_id 和 assistant_token_id。
不知道你们的低分是用没用，我想Chat模型既然是用来Chat，那应该按照Chat的模式来，加上这两个标识符来测评。

**Comment by Daisy5296** [comment]
同问。加上了user_token_id 和 assistant_token_id，指标仍然达不到官宣。希望官方能公布chat模型的评估方式。

**Comment by KelleyYin** [comment]
Chat 模型应该是需要加上Baichuan的prompt template的，这里的template是否一致啊？

**Comment by siliconx** [comment]
我也遇到了这个问题，CMMLU、CEval上都是四十多分。
Chat 模型需要设置prompt模板吗？
