### ISSUE TITLE
量化8的版本不能下载

### ISSUE THREAD

**Issue by running-frog** [baichuan-inc/Baichuan-13B#71]
https://huggingface.co/baichuan-inc/Baichuan-13B-Chat-int8

**Comment by heavenkiller2018** [comment]
the same problem. 另外, 如果想自己手动做int8量化，要如何处理，有谁能给下方案吗？

**Comment by wzwtime** [comment]
> https://huggingface.co/baichuan-inc/Baichuan-13B-Chat-int8

404

**Comment by GradientGuru** [comment]
现在是正常的。可能之前有短暂的设为 private

**Comment by FURYFOR** [comment]
https://huggingface.co/baichuan-inc/Baichuan-13B-Chat-int8,目前还是404呀

**Comment by lfxx** [comment]
> 现在是正常的。可能之前有短暂的设为 private

麻烦确认一下是否可以下载吧
