### ISSUE TITLE
如何保存和载入在线量化的模型？

### ISSUE THREAD

**Issue by edolele** [baichuan-inc/Baichuan-13B#78]
我使用下面的语句进行了保存model.save_pretrained("./model/baichuan-13b-8int", from_pt=True) 
然后载入测试了一下语句：
model = AutoModelForCausalLM.from_pretrained(
        "./model/baichuan-13b-8int",
        torch_dtype=torch.float16,
        trust_remote_code=True
    )

model = AutoModelForCausalLM.from_pretrained(
        "./model/baichuan-13b-8int",
        torch_dtype=torch.float16,
        device_map="auto",
        trust_remote_code=True
    )
但是都报错了，提示：
`Some weights of BaichuanForCausalLM were not initialized from the model checkpoint at ./model/baichuan-13b-8int and are newly initialized: ['model.layers.12.mlp.gate_proj.weight', 'model.layers.22.mlp.gate_proj.weight', 'model.layers.25.mlp.gate_proj.weight', 'model.layers.36.mlp.up_proj.weight', 'model.layers.2.mlp.up_proj.weight', 'model.layers.9.mlp.up_proj.weight', 'model.layers.39.mlp.up_proj.weight', 'model.layers.38.self_attn.W_pack.weight', 'model.layers.29.mlp.gate_proj.weight', 'model.layers.5.mlp.up_proj.weight', 'model.layers.30.mlp.gate_proj.weight', 'model.layers.20.mlp.gate_proj.weight', 'model.layers.29.self_attn.o_proj.weight', 'model.layers.34.mlp.gate_proj.weight', 'model.layers.10.self_attn.W_pack.weight', 'model.layers.8.self_attn.W_pack.weight', 'model.layers.24.mlp.up_proj.weight', 'model.layers.13.self_attn.o_proj.weight', 'model.layers.33.self_attn.o_proj.weight', 'model.layers.27.mlp.up_proj.weight', 'model.layers.26.self_attn.o_proj.weight', 'model.layers.18.self_attn.o_proj.weight', 'model.layers.16.mlp.down_proj.weight', 'model.layers.35.mlp.gate_proj.weight', 'model.layers.8.mlp.up_proj.weight', 'model.layers.26.self_attn.W_pack.weight', 'model.layers.25.self_attn.W_pack.weight', 'model.layers.34.mlp.up_proj.weight', 'model.layers.1.mlp.gate_proj.weight', 'model.layers.5.mlp.down_proj.weight', 'model.layers.24.self_attn.W_pack.weight', 'model.layers.9.mlp.down_proj.weight', 'model.layers.16.self_attn.W_pack.weight', 'model.layers.9.mlp.gate_proj.weight', 'model.layers.26.mlp.up_proj.weight', 'model.layers.22.mlp.up_proj.weight', 'model.layers.15.self_attn.o_proj.weight', 'model.layers.29.self_attn.W_pack.weight', 'model.layers.6.self_attn.o_proj.weight', 'model.layers.14.mlp.up_proj.weight', 'model.layers.31.mlp.gate_proj.weight', 'model.layers.4.self_attn.o_proj.weight', 'model.layers.8.self_attn.o_proj.weight', 'model.layers.18.mlp.down_proj.weight', 'model.layers.7.self_attn.o_proj.weight', 'model.layers.19.mlp.down_proj.weight', 'model.layers.12.mlp.up_proj.weight', 'model.layers.11.self_attn.W_pack.weight', 'model.layers.0.mlp.gate_proj.weight', 'model.layers.8.mlp.gate_proj.weight', 'model.layers.1.mlp.up_proj.weight', 'model.layers.33.mlp.up_proj.weight', 'model.layers.16.mlp.gate_proj.weight', 'model.layers.12.mlp.down_proj.weight', 'model.layers.23.self_attn.W_pack.weight', 'model.layers.1.self_attn.W_pack.weight', 'model.layers.10.mlp.gate_proj.weight', 'model.layers.22.mlp.down_proj.weight', 'model.layers.7.mlp.down_proj.weight', 'model.layers.36.mlp.gate_proj.weight', 'model.layers.23.self_attn.o_proj.weight', 'model.layers.12.self_attn.o_proj.weight', 'model.layers.37.mlp.up_proj.weight', 'model.layers.36.self_attn.o_proj.weight', 'model.layers.35.self_attn.W_pack.weight', 'model.layers.10.self_attn.o_proj.weight', 'model.layers.1.mlp.down_proj.weight', 'model.layers.20.mlp.up_proj.weight', 'model.layers.6.mlp.up_proj.weight', 'model.layers.13.mlp.gate_proj.weight', 'model.layers.3.self_attn.W_pack.weight', 'model.layers.17.mlp.down_proj.weight', 'model.layers.3.self_attn.o_proj.weight', 'model.layers.28.self_attn.o_proj.weight', 'model.layers.36.mlp.down_proj.weight', 'model.layers.7.self_attn.W_pack.weight', 'model.layers.11.self_attn.o_proj.weight', 'model.layers.5.self_attn.W_pack.weight', 'model.layers.31.mlp.down_proj.weight', 'model.layers.21.mlp.up_proj.weight', 'model.layers.26.mlp.gate_proj.weight', 'model.layers.37.mlp.down_proj.weight', 'model.layers.23.mlp.up_proj.weight', 'model.layers.29.mlp.up_proj.weight', 'model.layers.7.mlp.gate_proj.weight', 'model.layers.39.mlp.gate_proj.weight', 'model.layers.30.mlp.down_proj.weight', 'model.layers.18.mlp.gate_proj.weight', 'model.layers.37.mlp.gate_proj.weight', 'model.layers.24.mlp.down_proj.weight', 'model.layers.4.mlp.gate_proj.weight', 'model.layers.6.self_attn.W_pack.weight', 'model.layers.19.mlp.up_proj.weight', 'model.layers.14.mlp.gate_proj.weight', 'model.layers.33.self_attn.W_pack.weight', 'model.layers.7.mlp.up_proj.weight', 'model.layers.35.mlp.up_proj.weight', 'model.layers.12.self_attn.W_pack.weight', 'model.layers.20.self_attn.W_pack.weight', 'model.layers.35.self_attn.o_proj.weight', 'model.layers.11.mlp.gate_proj.weight', 'model.layers.0.mlp.up_proj.weight', 'model.layers.3.mlp.down_proj.weight', 'model.layers.20.mlp.down_proj.weight', 'model.layers.34.mlp.down_proj.weight', 'model.layers.2.self_attn.W_pack.weight', 'model.layers.0.mlp.down_proj.weight', 'model.layers.16.self_attn.o_proj.weight', 'model.layers.5.mlp.gate_proj.weight', 'model.layers.14.self_attn.W_pack.weight', 'model.layers.36.self_attn.W_pack.weight', 'model.layers.37.self_attn.W_pack.weight', 'model.layers.38.self_attn.o_proj.weight', 'model.layers.0.self_attn.W_pack.weight', 'model.layers.22.self_attn.o_proj.weight', 'model.layers.23.mlp.down_proj.weight', 'model.layers.4.mlp.down_proj.weight', 'model.layers.38.mlp.up_proj.weight', 'model.layers.39.mlp.down_proj.weight', 'model.layers.4.self_attn.W_pack.weight', 'model.layers.10.mlp.down_proj.weight', 'model.layers.25.mlp.up_proj.weight', 'model.layers.27.self_attn.o_proj.weight', 'model.layers.27.self_attn.W_pack.weight', 'model.layers.30.self_attn.W_pack.weight', 'model.layers.32.self_attn.o_proj.weight', 'model.layers.33.mlp.gate_proj.weight', 'model.layers.30.self_attn.o_proj.weight', 'model.layers.21.mlp.down_proj.weight', 'model.layers.17.mlp.gate_proj.weight', 'model.layers.6.mlp.down_proj.weight', 'model.layers.17.self_attn.o_proj.weight', 'model.layers.19.mlp.gate_proj.weight', 'model.layers.29.mlp.down_proj.weight', 'model.layers.4.mlp.up_proj.weight', 'model.layers.21.self_attn.W_pack.weight', 'model.layers.37.self_attn.o_proj.weight', 'model.layers.2.self_attn.o_proj.weight', 'model.layers.13.self_attn.W_pack.weight', 'model.layers.20.self_attn.o_proj.weight', 'model.layers.25.self_attn.o_proj.weight', 'model.layers.27.mlp.down_proj.weight', 'model.layers.9.self_attn.o_proj.weight', 'model.layers.32.mlp.down_proj.weight', 'model.layers.18.self_attn.W_pack.weight', 'model.layers.3.mlp.up_proj.weight', 'model.layers.25.mlp.down_proj.weight', 'model.layers.28.mlp.down_proj.weight', 'model.layers.31.self_attn.o_proj.weight', 'model.layers.38.mlp.gate_proj.weight', 'model.layers.30.mlp.up_proj.weight', 'model.layers.17.self_attn.W_pack.weight', 'model.layers.11.mlp.down_proj.weight', 'model.layers.1.self_attn.o_proj.weight', 'model.layers.23.mlp.gate_proj.weight', 'model.layers.15.mlp.up_proj.weight', 'model.layers.15.mlp.down_proj.weight', 'model.layers.28.mlp.up_proj.weight', 'model.layers.33.mlp.down_proj.weight', 'model.layers.22.self_attn.W_pack.weight', 'model.layers.39.self_attn.W_pack.weight', 'model.layers.38.mlp.down_proj.weight', 'model.layers.5.self_attn.o_proj.weight', 'model.layers.8.mlp.down_proj.weight', 'model.layers.19.self_attn.o_proj.weight', 'model.layers.21.self_attn.o_proj.weight', 'model.layers.31.mlp.up_proj.weight', 'model.layers.10.mlp.up_proj.weight', 'model.layers.14.self_attn.o_proj.weight', 'model.layers.2.mlp.down_proj.weight', 'model.layers.13.mlp.up_proj.weight', 'model.layers.34.self_attn.W_pack.weight', 'model.layers.39.self_attn.o_proj.weight', 'model.layers.3.mlp.gate_proj.weight', 'model.layers.2.mlp.gate_proj.weight', 'model.layers.28.mlp.gate_proj.weight', 'model.layers.34.self_attn.o_proj.weight', 'model.layers.19.self_attn.W_pack.weight', 'model.layers.14.mlp.down_proj.weight', 'model.layers.35.mlp.down_proj.weight', 'model.layers.6.mlp.gate_proj.weight', 'model.layers.27.mlp.gate_proj.weight', 'model.layers.24.mlp.gate_proj.weight', 'model.layers.15.self_attn.W_pack.weight', 'model.layers.26.mlp.down_proj.weight', 'model.layers.32.mlp.gate_proj.weight', 'model.layers.0.self_attn.o_proj.weight', 'model.layers.32.self_attn.W_pack.weight', 'model.layers.9.self_attn.W_pack.weight', 'model.layers.18.mlp.up_proj.weight', 'model.layers.28.self_attn.W_pack.weight', 'model.layers.13.mlp.down_proj.weight', 'model.layers.11.mlp.up_proj.weight', 'model.layers.21.mlp.gate_proj.weight', 'model.layers.16.mlp.up_proj.weight', 'model.layers.31.self_attn.W_pack.weight', 'model.layers.17.mlp.up_proj.weight', 'model.layers.15.mlp.gate_proj.weight', 'model.layers.24.self_attn.o_proj.weight', 'model.layers.32.mlp.up_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.`

**Comment by jameswu2014** [comment]
目前int8模型可以这样存储，不能这么载入。后续我们会开发int8的离线版本
