### ISSUE TITLE
关于 forward attention_mask 参数

### ISSUE THREAD

**Issue by Sanster** [baichuan-inc/Baichuan-13B#79]
`BaichuanModel.forward` 不支持 attention_mask，对于长度不同的 prompt batch 输入会不会有影响？

https://huggingface.co/baichuan-inc/Baichuan-13B-Base/blob/43fb20e1c7d9a19118ed0ae8076061dba775273a/modeling_baichuan.py#L256

**Comment by GradientGuru** [comment]
已经更新，请在hugging face pull 最新代码
