### ISSUE TITLE
关于位置编码

### ISSUE THREAD

**Issue by jiangix-paper** [baichuan-inc/Baichuan-13B#8]
请问为何在13B的时候将位置编码从ROPE改为Alibi了。如果从长度外推的角度来考虑，我们最近看论文Rope通过插值也能做到很好的长度外推，请问改成Alibi是基于其他的一些考虑吗？谢谢~

**Comment by jiangix-paper** [comment]
看到您的readme中有提到说会对推理有较高的速度提升，请问在效果方面。是否Alibi与Rope相差不大呢？

**Comment by jeffchy** [comment]
Rope is much easier to support Flash-attention, could you please provide code that support flash attention training using alibi?

**Comment by EricLingRui** [comment]
> 请问为何在13B的时候将位置编码从ROPE改为Alibi了。如果从长度外推的角度来考虑，我们最近看论文Rope通过插值也能做到很好的长度外推，请问改成Alibi是基于其他的一些考虑吗？谢谢~

实际上，Alibi位置编码也具备RoPe的[位置插值](https://arxiv.org/pdf/2306.15595.pdf)特性，以下是Baichuan-13B-Chat在shareGPT-zh 1w token以上的样本做的实验。可以看到，插值的效果是优于外推的，并且插值并没有微调。
![CE6F49A3-4FC7-4ec0-B7E8-B58310D30B6D](https://github.com/baichuan-inc/Baichuan-13B/assets/26210791/9b15b363-8352-4c61-912b-7478c8ea3d2f)

也可以看到，ALiBi的外推能力在本测试集上是优于RoPe的，之前的7b模型在8192的点为上PPL是34+，而这里是2.24。

图中还有个有趣的实验，就是插值是按静态插值（按固定最大长度计算缩放比例）和动态插值（按当前文本长度计算缩放比例）。如果这个实验靠谱，可能会得出几个猜想结论：
1.  想办法把超长的推理文本的位置编码压缩到模型训练的最大长度之内，模型的表现就会变好。
2.  在1.的基础上，统计SFT数据token的长度分布，将推理文本token长度压缩到该分布密度最高的长度上，模型表现最佳。

以上结论和猜想仅供参考，实践需要自己根据自己的数据做测试。

**Comment by wn1652400018** [comment]
> Rope is much easier to support Flash-attention, could you please provide code that support flash attention training using alibi?
请问为何rope会更容易支持flash-attention.我之前尝试用flashattention训练mpt-7b,最后也没有成功。

**Comment by Sanster** [comment]
@wn1652400018 baichuan-7b 训练代码中就是 RoPE + xformers https://github.com/baichuan-inc/Baichuan-7B/blob/4b73fddd1c5cd474b897a70e23b606db85b1fcfe/models/modeling_baichuan.py#L223

**Comment by wn1652400018** [comment]
> @wn1652400018 baichuan-7b 训练代码中就是 RoPE + xformers https://github.com/baichuan-inc/Baichuan-7B/blob/4b73fddd1c5cd474b897a70e23b606db85b1fcfe/models/modeling_baichuan.py#L223
baichuan-7b我知道是rope。百川13b是alibi，本仓库的代码能让baichuan-13b用flash-attention训练和推理吗

**Comment by wn1652400018** [comment]
百川13b自己介绍时不是说了他们使用flashattention的吗😂



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月13日(周四) 晚上6:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [baichuan-inc/Baichuan-13B] 关于位置编码 (Issue #8)




 
推理看到有人试过 alibi+xformers 可以，但是训练不行：facebookresearch/xformers#700 (comment)

**Comment by ShinichR** [comment]
> > 请问为何在13B的时候将位置编码从ROPE改为Alibi了。如果从长度外推的角度来考虑，我们最近看论文Rope通过插值也能做到很好的长度外推，请问改成Alibi是基于其他的一些考虑吗？谢谢~
> 
> 实际上，Alibi位置编码也具备RoPe的[位置插值](https://arxiv.org/pdf/2306.15595.pdf)特性，以下是Baichuan-13B-Chat在shareGPT-zh 1w token以上的样本做的实验。可以看到，插值的效果是优于外推的，并且插值并没有微调。 ![CE6F49A3-4FC7-4ec0-B7E8-B58310D30B6D](https://user-images.githubusercontent.com/26210791/252632039-9b15b363-8352-4c61-912b-7478c8ea3d2f.png)
> 
> 也可以看到，ALiBi的外推能力在本测试集上是优于RoPe的，之前的7b模型在8192的点为上PPL是34+，而这里是2.24。
> 
> 图中还有个有趣的实验，就是插值是按静态插值（按固定最大长度计算缩放比例）和动态插值（按当前文本长度计算缩放比例）。如果这个实验靠谱，可能会得出几个猜想结论：
> 
> 1. 想办法把超长的推理文本的位置编码压缩到模型训练的最大长度之内，模型的表现就会变好。
> 2. 在1.的基础上，统计SFT数据token的长度分布，将推理文本token长度压缩到该分布密度最高的长度上，模型表现最佳。
> 
> 以上结论和猜想仅供参考，实践需要自己根据自己的数据做测试。

这里Alibi静动态插值的code方便share吗

**Comment by piekey1994** [comment]
> > 请问为何在13B的时候将位置编码从ROPE改为Alibi了。如果从长度外推的角度来考虑，我们最近看论文Rope通过插值也能做到很好的长度外推，请问改成Alibi是基于其他的一些考虑吗？谢谢~
> 
> 实际上，Alibi位置编码也具备RoPe的[位置插值](https://arxiv.org/pdf/2306.15595.pdf)特性，以下是Baichuan-13B-Chat在shareGPT-zh 1w token以上的样本做的实验。可以看到，插值的效果是优于外推的，并且插值并没有微调。 ![CE6F49A3-4FC7-4ec0-B7E8-B58310D30B6D](https://user-images.githubusercontent.com/26210791/252632039-9b15b363-8352-4c61-912b-7478c8ea3d2f.png)
> 
> 也可以看到，ALiBi的外推能力在本测试集上是优于RoPe的，之前的7b模型在8192的点为上PPL是34+，而这里是2.24。
> 
> 图中还有个有趣的实验，就是插值是按静态插值（按固定最大长度计算缩放比例）和动态插值（按当前文本长度计算缩放比例）。如果这个实验靠谱，可能会得出几个猜想结论：
> 
> 1. 想办法把超长的推理文本的位置编码压缩到模型训练的最大长度之内，模型的表现就会变好。
> 2. 在1.的基础上，统计SFT数据token的长度分布，将推理文本token长度压缩到该分布密度最高的长度上，模型表现最佳。
> 
> 以上结论和猜想仅供参考，实践需要自己根据自己的数据做测试。

同求插值的code，谢谢大佬
