### ISSUE TITLE
加载模型太慢了，请问有优化办法吗？

### ISSUE THREAD

**Issue by mosluo** [baichuan-inc/Baichuan-13B#80]
执行这段代码，加载模型，但是模型加载很慢

model = AutoModelForCausalLM.from_pretrained(
    pretrain_path,
    device_map="auto",
    torch_dtype=torch.float16,
    trust_remote_code=True,
)

**Comment by GradientGuru** [comment]
请问有多慢

**Comment by mosluo** [comment]
10分钟

**Comment by GradientGuru** [comment]
可以试试直接加载到CPU的速度做对比。感觉是磁盘问题。这边测试通常需要十几秒钟就可以加载了
