### ISSUE TITLE
int8/int4 模型不存在

### ISSUE THREAD

**Issue by QuchenFu** [baichuan-inc/Baichuan-13B#88]
int8/int4 模型不存在
https://huggingface.co/baichuan-inc/Baichuan-13B-Chat-int4

**Comment by jameswu2014** [comment]
我们已经传上hf了，只是在等待一个时机开放出来，敬请关注

**Comment by ZhuoRoger** [comment]
请问什么时候开放呢？

**Comment by jnulzl** [comment]
2023/8/9 还未开放

**Comment by stuarthe** [comment]
2023/8/24还没开放

**Comment by ZhuoRoger** [comment]
申请尽快开放呢

**Comment by kovogo** [comment]
2023/8/31 还没开放

同样因为显存限制，需要量化好的int8，方便加载和推理。 请尽快开放~~
