### ISSUE TITLE
想让模型读万卷书，应该怎么做？

### ISSUE THREAD

**Issue by CanvaChen** [baichuan-inc/Baichuan-13B#94]
1. 想给模型喂各种书籍，比如小说、教科书等，希望微调完是一名接受过高等教育的模型。
2. 希望该模型部署之后，还能比较快地学习新的书，不需要重新训练。

有没有成本相对较低的实现方案？

**Comment by red4army** [comment]
1. 通过微调
2. 想不重新训练/微调的话，可以使用langchain套件

**Comment by hanyi-zou** [comment]
你要学习书本的知识，而不是需要指令对齐，所以你应该使用书籍数据进行无监督的二次预训练，以学习书籍知识
