### ISSUE TITLE
KeyError: 'st.session_state has no key "messages". Did you forget to initialize it? 

### ISSUE THREAD

**Issue by tommyjex** [baichuan-inc/Baichuan-13B#96]
2023.7.23，今天上午运行web_demo.py，出现st.session_state报错，代码没变化，昨天还能正常运行。有人也遇到过吗

Traceback (most recent call last):
  File "/root/llm/baichuan-13B/Baichuan-13B/web_demo.py", line 72, in <module>
    main()
  File "/root/llm/baichuan-13B/Baichuan-13B/web_demo.py", line 51, in main
    messages = init_chat_history()
  File "/root/llm/baichuan-13B/Baichuan-13B/web_demo.py", line 47, in init_chat_history
    return st.session_state.messages
  File "/root/anaconda3/envs/baichuan/lib/python3.10/site-packages/streamlit/runtime/state/session_state_proxy.py", line 121, in __getattr__
    raise AttributeError(_missing_attr_error_message(key))
AttributeError: st.session_state has no attribute "messages". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

**Comment by tommyjex** [comment]
对应的代码片段如下
`def init_chat_history():
    with st.chat_message("assistant", avatar='🤖'):
        st.markdown("您好，我是百川大模型，很高兴为您服务🥰")

    if "messages" in st.session_state:
        for message in st.session_state.messages:
            avatar = '🧑‍💻' if message["role"] == "user" else '🤖'
            with st.chat_message(message["role"], avatar=avatar):
                st.markdown(message["content"])
    else:
        st.session_state.messages = []

    return st.session_state.messages`

**Comment by MMMartt** [comment]
你是不是没有用 `streamlit run web_demo.py` 而是 `python web_demo.py` 启动的，如果是后者会报这种错。

**Comment by tommyjex** [comment]
> 你是不是没有用 `streamlit run web_demo.py` 而是 `python web_demo.py` 启动的，如果是后者会报这种错。

是的，感谢，已解决
